version: '3.9'
services:

  app:
    image: 'stock-api'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-api
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATA_REDIS_HOST: "redis"  
      SPRING_DATA_REDIS_PORT: "6379"   
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/stockdb"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "create"
    ports:
      - "8080:8080"
    networks:
      - postgres
      - redis  

  db:
    container_name: stock-db
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "stockdb"
      PG_DATA: "/data/postgres"
    ports:
      - "2402:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: stock-token-control
    image: redis:7.2.4-alpine
    restart: unless-stopped
    ports:
      - "63001:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - "./infra/cache:/data"
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
